### ISSUE TITLE
Java SDK 11.0.99 or above is required when using Android SDK Build-Tools 26.

### ISSUE THREAD

**Issue by Chesfiy** [santedb/santedb-dc-android#1]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Java SDK 11.0.99 or above is required when using Android SDK Build-Tools 26.	SanteDB.DisconnectedClient.Android

**Comment by justin-fyfe** [comment]
Not a bug with SanteDB bug with Xamarin (see: https://github.com/xamarin/xamarin-android/issues/4853) or can be the JDK settings on your build environment. 

Editing the JDK check on the Xamarin targets file with your version of Java (as indicated in the xamarin bug) or pointing your JDK path to a version indicated, or updating Xamarin installation may resolve.

If the issue persists please consult Xamarin project discussions/issue tracker.
